### ISSUE TITLE
Script to regenerate `data.json` file?

### ISSUE THREAD

**Issue by TooTallNate** [substack/node-ent#23] opened 2015-02-09 20:26 UTC
@substack How was the `data.json` file generated? I'm noticing a strange entry in there:  `&ZeroWidthSpace;`, which I can't seem to find referenced anywhere on the net.

Additionally, the `HTML::Entities` link on the readme is now a 404: http://cpansearch.perl.org/src/GAAS/HTML-Parser-3.68/lib/HTML/Entities.pm

It seems like the current version is 3.71: http://cpansearch.perl.org/src/GAAS/HTML-Parser-3.71/lib/HTML/Entities.pm

Seems like the link is kind of fragile :( But on a more relevant note, perhaps this new version has more accurate entities inside and we need to regenerate the `data.json` file based off of this new version?

**Comment by TooTallNate** [comment] 2015-02-11 16:33
This seems like the most official source: http://dev.w3.org/html5/html-author/charref

Suprisingly, `&ZeroWidthSpace;` _is_ defined there, just appears to not be supported by Chrome.

**Comment by mathiasbynens** [comment] 2015-02-11 19:44
@TooTallNate 

> This seems like the most official source: http://dev.w3.org/html5/html-author/charref

Not really — https://html.spec.whatwg.org/multipage/syntax.html#named-character-references is. And the list is [available in JSON format too](https://html.spec.whatwg.org/entities.json). (Btw, did you ever check out [_he_](https://github.com/mathiasbynens/he)? All this is linked to in its source code.)

> Surprisingly, `&ZeroWidthSpace;` is defined there, just appears to not be supported by Chrome, Firefox.

What makes you say that? `&ZeroWidthSpace;` is [correctly implemented](https://mathias.html5.org/tests/html/named-character-references/) by both Chromium and Firefox.

**Comment by mathiasbynens** [comment] 2015-02-11 19:45
Also, this seems to be a duplicate of #8.

**Comment by TooTallNate** [comment] 2015-02-11 19:50
Good to know about the JSON list, thanks :)

>  Btw, did you ever check out he? All this is linked to in its source code.

I did. My main gripe was that I can't only require the encoder, for situations where I only want that.

> What makes you say that? &ZeroWidthSpace; is correctly implemented by both Chromium and Firefox.

Doh! Ya I realized this after a bit more digging. The real source of my issue is the WordPress backend, which apparently doesn't have an up-to-date list of the HTML5 entities. So nothing related to an issue with this module in the end.

> Heads up: the credits section in the README should be tweaked now that this is merged, since the HTML entity tables are no longer lifted from perl's `HTML::Entities`.

Good catch, I'll update the README.

**Closed** 2015-02-11 19:59 UTC
